export const SET_ERRORS = "SET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const NOTIFICATIONS_LOADING = "NOTIFICATION_LOADING";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const SET_TODOLISTS = "SET_TODOLISTS";
export const TODOLISTS_LOADING = "TODOLISTS_LOADING";
export const REMOVE_TODOLIST = "REMOVE_TODOLIST";
export const ADD_TODOLIST = "ADD_TODOLIST";
export const SET_TODOS = "SET_TODOS";
export const TODOS_LOADING = "TODOS_LOADING";
export const REMOVE_TODO = "REMOVE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const ADD_TODO = "ADD_TODO";


