export const SET_ERRORS = "SET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const NOTIFICATIONS_LOADING = "NOTIFICATION_LOADING";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const SET_TODOLISTS = "SET_TODOLISTS";
export const TODOLISTS_LOADING = "TODOLISTS_LOADING";
